version: "3.9"

services:

  grafana:
    image: "grafana/grafana-oss:10.2.2"
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /metrics-main-dev/grafana-config:/etc/grafana
      - /metrics-main-dev/grafana-data:/var/lib/grafana
    user: "root"
    environment:
      GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8081/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
      GF_LOG_FILTERS: "rendering:debug"
      TZ: "Europe/Moscow"
    networks:
      - default
          
  grafana-image-renderer:
    image: "grafana/grafana-image-renderer:3.9.0"
    container_name: grafana-image
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
          
  prometheus:
    image: "prom/prometheus:v2.48.0"
    container_name: prometheus
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 9090:9090
    volumes:
      - /metrics-main-dev/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /metrics-main-dev/config/web-config.yaml:/etc/prometheus/web-config.yaml:ro
      - /metrics-main-dev/prometheus-data:/prometheus
    user: "root"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.config.file=/etc/prometheus/web-config.yaml"
      - "--storage.tsdb.retention.time=2d"
    networks:
      - default
          
  pushgateway:
    image: "prom/pushgateway:v1.6.2"
    container_name: pushgateway
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 9091:9091
    volumes:
      - /metrics-main-dev/config/web-config.yaml:/etc/prometheus/web-config.yaml:ro
    command:
      - "--web.config.file=/etc/prometheus/web-config.yaml"
    networks:
      - default
          
  loki:
    image: "grafana/loki:2.9.0"
    container_name: loki
    environment:
      TZ: "Europe/Moscow"
    #  - "3100:3100" port closed because loki does not support basic auth
    volumes:
      - /metrics-main-dev/config/loki.yaml:/etc/loki/loki.yaml:ro
      - /metrics-main-dev/loki-data:/loki
    command: 
      - "--config.file=/etc/loki/loki.yaml"
    user: "root"
    networks:
      - default
          
  promtail:
    image: "grafana/promtail:2.9.0"
    container_name: promtail
    volumes:
      - /metrics-main-dev/config/promtail.yaml:/etc/promtail/promtail.yaml:ro
      - /metrics-main-dev/promtail-data:/var/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    environment:
      HOST_HOSTNAME: "{{.Node.Hostname}}"
      TZ: "Europe/Moscow"
    command:
      - "--config.file=/etc/promtail/promtail.yaml"
      - "--config.expand-env=true"
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
